### ISSUE TITLE
Operation cannot be fullfilled on namespaces "rio-system"

### ISSUE THREAD

**Issue by Lello1987** [rancher/rio#950] opened 2019-12-19 11:33 UTC
**Describe the bug**
When I try to uninstall rio:

Deleting System Namespace rio-system...
FATA[0000] Operation canot be fullfilled on namespaces "rio-system: The system is ensuring all content is removed from this namespace. Upon completion, this namespace will automatically be purged by the system.

**To Reproduce**
1. rio uninstall
2. ERROR

**Expected behavior**
Uninstall rio

**Kubernetes version & type (GKE, on-prem)**: `kubectl version`
```
v1.16.3
```

**Comment by rancher-max** [comment] 2019-12-20 17:52
@Lello1987 In the upcoming release of v0.7.0 we are fixing a few of the issues with the uninstall, which will hopefully help fix this error in the future. There may still be some cases that you see this though due to how finalizers work in kubernetes. If you run `kubectl get namespace` I suspect that the `rio-system` namespace is stuck in `Terminating`. This issue should help you resolve that: https://github.com/kubernetes/kubernetes/issues/60807

Also, we had a similar issue and a helpful comment from a user that I have found does the trick when this happens to me: https://github.com/rancher/rio/issues/724#issuecomment-555773526 (replace the IP and port with your IP and port if not local)

**Comment by davidnuzik** [comment] 2020-01-02 22:01
Should be fixed with v0.7.0; if you still observe this problem and it's reproduceable please let us know.

**Closed by davidnuzik** 2020-01-02 22:01 UTC
Labels: [zube]: Done, bug
