### ISSUE TITLE
rio-system namespace not always removed from kubernetes in k3s cluster [v0.6.0-alpha.4]

### ISSUE THREAD

**Issue by izaac** [rancher/rio#724] opened 2019-11-09 00:21 UTC
**Describe the bug**
I install and then uninstall rio v0.6.0-alpha.4 And then when trying a new installation I get an error because the `rio-system` namespace is being terminated.

**To Reproduce**
1. Install rio `v0.6.0-alpha.4`
2. Uninstall when it's finished with installation.
3. Try installing again.

Result:

```bash
Deploying Rio control plane....
FATA[0002] failed to create rio-system/rio-controller-serviceaccount /v1, Kind=ServiceAccount for  rio-system: serviceaccounts "rio-controller-serviceaccount" is forbidden: unable to create new content in namespace rio-system because it is being terminated, failed to create rio-system/rio-api-validator /v1, Kind=Secret for  rio-system: secrets "rio-api-validator" is forbidden: unable to create new content in namespace rio-system because it is being terminated, failed to create rio-system/rio-api-validator /v1, Kind=Service for  rio-system: services "rio-api-validator" is forbidden: unable to create new content in namespace rio-system because it is being terminated, failed to create rio-system/rio-controller apps/v1, Kind=Deployment for  rio-system: deployments.apps "rio-controller" is forbidden: unable to create new content in namespace rio-system because it is being terminated, failed to create rio-system/rio-config /v1, Kind=ConfigMap for  rio-system: configmaps "rio-config" is forbidden: unable to create new content in namespace rio-system because it is being terminated
```

k3s Setup one master and two workers.

```bash
k get nodes
NAME                 STATUS   ROLES    AGE     VERSION
izaac-k3s-master     Ready    master   8m56s   v1.16.2-k3s.1
izaac-k3s-worker-1   Ready    <none>   39s     v1.16.2-k3s.1
izaac-k3s-worker-2   Ready    <none>   9s      v1.16.2-k3s.1
```

**Expected behavior**

Being able to install rio after an uninstall.

**Kubernetes version & type (GKE, on-prem)**: `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2-k3s.1", GitCommit:"b8b17ba55f20e590df507fce333dfee13ab438c6", GitTreeState:"clean", BuildDate:"2019-10-16T05:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
Type:
**Rio version**: `rio info`
```
Not available
```
**Additional context**
`rio systemlogs`
output:
```
Not available
```

**Comment by StrongMonkey** [comment] 2019-11-11 16:09
@izaac This is expected, you have to wait for `rio-system` namespace to be deleted completely before reinstall. If you wait, does `rio-system` eventually gets deleted?

**Comment by izaac** [comment] 2019-11-11 16:14
@StrongMonkey I should've mentioned that the namespace doesn't get deleted. It stays there, this happens to me most of the time in k3s clusters.

**Comment by StrongMonkey** [comment] 2019-11-11 21:23
Probably not going to fix this in v0.6.0. Moved to v0.6.x

**Comment by swoldanski** [comment] 2019-11-20 00:06
Lifesaver found in web before:

If you have many namespaces stuck in Terminating, you can automate this:

`kubectl get ns | grep Terminating | awk '{print $1}' | xargs  -n1 -- bash -c 'kubectl get ns "$0" -o json | jq "del(.spec.finalizers[0])" > "$0.json"; curl -k -H "Content-Type: application/json" -X PUT --data-binary @"$0.json" "http://127.0.0.1:8001/api/v1/namespaces/$0/finalize" '`

make sure that all namespaces that you want the finalizer removed are indeed Terminating.

You need the kubectl proxy running and jq for the above to work.

**Comment by rancher-max** [comment] 2020-02-04 19:48
I can't reproduce this anymore in v0.7.0. Closing issue, but if anyone is able to reproduce it reliably in the latest version of Rio, please reopen or create a new issue with the steps taken.

**Closed by rancher-max** 2020-02-04 19:48 UTC
Labels: [zube]: To Test, bug
