### ISSUE TITLE
run --dnsoption, --dnssearch & --dns not saving to kubernetes deployment

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rio#320] opened 2019-07-03 00:00 UTC
Version - v0.2.0-rc1

Steps:
1.  rio run -n nsp/test1 --dnsoption debug --dnssearch example.com --dns 1.1.1.1 nginx
2.  kubectl get -n nsp -o=json deployment/test1

Results:  The options are not being saved in the dnsConfig

**Comment by StrongMonkey** [comment] 2019-07-09 17:09
It turns out that when enabling service mesh, istio sidecar injection automatically overrides the dnsConfig of original deployment.

**Comment by tfiduccia** [comment] 2019-08-07 18:13
@StrongMonkey - I'm not sure what the question is?

**Comment by StrongMonkey** [comment] 2019-08-07 18:36
@tfiduccia From my observation you can't not set custom dns config if you have enabled istio sidecar for your workload. The sidecar injection will always override dns config. Will dig into this further.

**Comment by izaac** [comment] 2019-10-11 20:01
@StrongMonkey @davidnuzik I'm not able to reproduce this in `v0.5.0` I've tried in both `linkerd` and `istio` mesh modes.

Any suggestions on setups for trying to reproduce before closing this issue?

**Comment by davidnuzik** [comment] 2019-10-15 16:17
Thanks @izaac the hope was that you would not be able to reproduce in v0.5.0 due to change in since v0.2.0 we can probably close the issue.

**Comment by izaac** [comment] 2019-10-15 16:47
Closing 👍

**Closed by izaac** 2019-10-15 16:47 UTC
Labels: [zube]: Next Up, question
