### ISSUE TITLE
Service Mesh Fails on a fresh install after a few days.

### ISSUE THREAD

**Issue by lucidprogrammer** [rancher/rio#880] opened 2019-12-02 00:52 UTC
**Describe the bug**
Here is the view from linkerd dashboard.
![image](https://user-images.githubusercontent.com/6227632/69923407-88c09e80-149c-11ea-973f-3d02d96d297b.png)

![image](https://user-images.githubusercontent.com/6227632/69923427-ae4da800-149c-11ea-8429-1f4aef64cfdb.png)

`$ kubectl -n rio-system get pods`

```
NAME                                READY   STATUS      RESTARTS   AGE
autoscaler-664c595f9c-hqf8m         2/2     Running     1          3d17h
buildkitd-665d7d7978-qq8vg          2/2     Running     0          3d17h
cert-manager-846cb89b88-gn7qv       2/2     Running     1          3d17h
dashboard-7f4d7f747f-47mn9          2/2     Running     3          3d17h
gateway-proxy-v2-86896f6489-8g9nl   2/2     Running     0          3d17h
gateway-v2-5fdf4545bc-29hbh         2/2     Running     1          3d17h
gloo-6657cbbb49-qpzwr               2/2     Running     1          3d17h
linkerd-install-gjtw8-nlhxf         0/1     Error       0          3h49m
linkerd-install-gjtw8-z45mf         0/1     Completed   0          3h49m
rio-controller-cd665cd96-72p9w      1/1     Running     2          3d17h
socat-624f9                         1/1     Running     0          3d17h
socat-fxfcs                         1/1     Running     0          3d17h
socat-hfqvx                         1/1     Running     0          3d17h
webhook-56f455fb89-mvldp            2/2     Running     1          3d17h
```

**To Reproduce**
1. 

**Expected behavior**

Can somebody explain why https://github.com/rancher/rio/blob/master/modules/linkerd/feature/feature.go has this
```
func Register(ctx context.Context, rContext *types.Context) error {
	cmClient := rContext.Core.Core().V1().ConfigMap()
	linkerdUpgrade := ""
	if _, err := cmClient.Get(linkerdNamespace, linkerdConfigName, metav1.GetOptions{}); err == nil {
		linkerdUpgrade = "\"TRUE\""
	}
```
`kubectl -n rio-system get job.batch`
Above gives the job which does it.

Anyway this is a serious deal breaker at least in our usage. After this autoscale and other functionalities does not work.
**Kubernetes version & type (GKE, on-prem)**: `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:46:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-eks-41be3d", GitCommit:"41be3d46034bc1d637f82d35a6eee5df7efc5142", GitTreeState:"clean", BuildDate:"2019-11-20T17:19:16Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

```
Type:
**Rio version**: `rio info`
```
latest
```
**Additional context**
`rio systemlogs`
output:
```

```

**Comment by StrongMonkey** [comment] 2019-12-02 05:21
Can you explain what functionality is broken after this? I think an exclamation mark is caused by the fact that not all pods in rio-system are mesh, not sign of things are broken tho.

**Comment by StrongMonkey** [comment] 2019-12-02 05:27
Also a good point to check if we should run upgrade job automatically in rio-controller. Need to be discussed further.

**Comment by lucidprogrammer** [comment] 2019-12-02 06:15
yes, normally in a production system, its the devops who decides whether to upgrade something or not. Or externalise this, so if somebody wants it to auto upgrade, let them provide the variable. Not a default functionality

**Comment by davidnuzik** [comment] 2019-12-05 21:38
Note: Can be a part of the lite install effort (don't upgrade).

**Comment by rancher-max** [comment] 2019-12-11 16:12
I believe this is fixed in latest master. Linkerd no longer auto upgrades by default, and it appears the mesh no longer gives the single "error" pod which is what caused the red exclamation mark in rio-system namespace from the linkerd dashboard.

**Closed** 2019-12-11 16:19 UTC
Labels: [zube]: Working, question
