### ISSUE TITLE
Can't remove service after using `rio up`

### ISSUE THREAD

**Issue by michaelerobertsjr** [rancher/rio#582] opened 2019-10-20 16:30 UTC
**Describe the bug**
After using `rio up` I am not able to use `rio rm` even after setting the scale to 0

**To Reproduce**
1. Create a Riofile
1. Run `rio up`
1. Run `rio rm default/<service_name>`

**Expected behavior**
Should stop and remove the service

**Kubernetes version & type (GKE, on-prem)**: `kubectl version`
Using RKS on AWS.

Type:
**Rio version**: `rio info`
```
io Version: v0.5.0 (303f3652)
Rio CLI Version: v0.5.0 (303f3652)
Cluster Domain: 9nfx9n.on-rio.io
Cluster Domain IPs: 34.222.146.200,54.148.187.112,54.244.193.155
System Namespace: rio-system

System Components:
activator status: running
autoscaler status: running
build-controller status: running
buildkitd-dev status: running
cert-manager status: running
controller status: running
gateway status: running
istio-pilot status: running
registry status: running
webhook status: running
```
**Additional context**
`rio systemlog`
output:
```

```

**Comment by cbron** [comment] 2019-10-20 16:36
This is likely a duplicate of https://github.com/rancher/rio/issues/521

**Comment by rancher-max** [comment] 2019-10-21 16:51
This is because the stack (Riofile) controls the service, so it recreates it when it notices it is down. To delete the service, you can delete the stack (`rio stack` --> `rio rm <stackname>`) but that will delete everything created with that Riofile. 

Alternatively, you can simply remove the service from the Riofile.

**Closed by rancher-max** 2019-10-21 16:51 UTC
Labels: bug
